# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
@EXPLICIT
https://repo.anaconda.com/pkgs/main/linux-64/_tflow_select-2.2.0-eigen.conda
https://conda.anaconda.org/conda-forge/linux-64/_libgcc_mutex-0.1-conda_forge.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/blas-1.0-mkl.conda
https://conda.anaconda.org/conda-forge/linux-64/ca-certificates-2023.5.7-hbcca054_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/ld_impl_linux-64-2.38-h1181459_1.conda
https://conda.anaconda.org/conda-forge/linux-64/libgfortran5-13.1.0-h15d22d2_0.conda
https://conda.anaconda.org/conda-forge/linux-64/libstdcxx-ng-13.1.0-hfd8a6a1_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pandoc-2.12-h06a4308_3.conda
https://repo.anaconda.com/pkgs/main/noarch/tzdata-2023c-h04d1e81_0.conda
https://conda.anaconda.org/conda-forge/linux-64/libgfortran-ng-13.1.0-h69a702a_0.conda
https://conda.anaconda.org/conda-forge/linux-64/libgomp-13.1.0-he5830b7_0.conda
https://conda.anaconda.org/conda-forge/linux-64/_openmp_mutex-4.5-2_gnu.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libgcc-ng-13.1.0-he5830b7_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/abseil-cpp-20211102.0-hd4dd3e8_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/bzip2-1.0.8-h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/c-ares-1.19.0-h5eee18b_0.conda
https://conda.anaconda.org/conda-forge/linux-64/cudatoolkit-11.2.2-hc23eb0c_12.conda
https://repo.anaconda.com/pkgs/main/linux-64/expat-2.4.9-h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/flatbuffers-2.0.0-h2531618_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/giflib-5.2.1-h5eee18b_3.conda
https://repo.anaconda.com/pkgs/main/linux-64/gsl-2.7.1-h6e86dc7_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/icu-58.2-he6710b0_3.conda
https://repo.anaconda.com/pkgs/main/linux-64/jpeg-9e-h5eee18b_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/lerc-3.0-h295c915_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libbrotlicommon-1.0.9-h5eee18b_7.conda
https://repo.anaconda.com/pkgs/main/linux-64/libdeflate-1.17-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libev-4.33-h7f8727e_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/libffi-3.4.4-h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libuuid-1.41.5-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libwebp-base-1.2.4-h5eee18b_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/libxcb-1.15-h7f8727e_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/lz4-c-1.9.4-h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/make-4.2.1-h1bed415_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/ncurses-6.4-h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/nspr-4.35-h6a678d5_0.conda
https://conda.anaconda.org/conda-forge/linux-64/openssl-1.1.1u-hd590300_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pcre-8.45-h295c915_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pkg-config-0.29.2-h1bed415_8.conda
https://repo.anaconda.com/pkgs/main/linux-64/re2-2022.04.01-h295c915_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/snappy-1.1.9-h295c915_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/tbb-2021.8.0-hdb19cb5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/xz-5.4.2-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/yaml-0.2.5-h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/yaml-cpp-0.7.0-h295c915_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/zlib-1.2.13-h5eee18b_0.conda
https://conda.anaconda.org/conda-forge/linux-64/cudnn-8.1.0.77-h90431f1_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/glib-2.69.1-he621ea3_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/hdf5-1.10.6-h3ffc7dd_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/intel-openmp-2023.1.0-hdb19cb5_46305.conda
https://repo.anaconda.com/pkgs/main/linux-64/libbrotlidec-1.0.9-h5eee18b_7.conda
https://repo.anaconda.com/pkgs/main/linux-64/libbrotlienc-1.0.9-h5eee18b_7.conda
https://repo.anaconda.com/pkgs/main/linux-64/libedit-3.1.20221030-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libevent-2.1.12-h8f2d780_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libllvm10-10.0.1-hbcb73fb_5.conda
https://repo.anaconda.com/pkgs/main/linux-64/libllvm14-14.0.6-hdb19cb5_3.conda
https://repo.anaconda.com/pkgs/main/linux-64/libnghttp2-1.52.0-ha637b67_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/libpng-1.6.39-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libprotobuf-3.20.3-he621ea3_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libssh2-1.10.0-h37d81fd_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/libxml2-2.9.14-h74e7548_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/readline-8.2-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/swig-4.0.2-h295c915_4.conda
https://repo.anaconda.com/pkgs/main/linux-64/tk-8.6.12-h1ccaba5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/zstd-1.5.5-hc292b87_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/brotli-bin-1.0.9-h5eee18b_7.conda
https://repo.anaconda.com/pkgs/main/linux-64/dbus-1.13.18-hb2f20db_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/freetype-2.12.1-h4a9f257_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/grpc-cpp-1.46.1-h33aed49_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/gstreamer-1.14.1-h5eee18b_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/krb5-1.19.4-h568e23c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libarchive-3.4.2-h5de8990_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/libclang-10.0.1-default_hb85057a_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/libtiff-4.5.0-h6a678d5_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/libxkbcommon-1.0.1-hfa300c1_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libxslt-1.1.35-h4e12654_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl-2023.1.0-h6d00ec8_46342.conda
https://repo.anaconda.com/pkgs/main/linux-64/sqlite-3.41.2-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/brotli-1.0.9-h5eee18b_7.conda
https://repo.anaconda.com/pkgs/main/linux-64/fontconfig-2.14.1-h52c9d5c_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/gst-plugins-base-1.14.1-h6a678d5_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/lcms2-2.12-h3be6417_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libcurl-7.88.1-h91b91d3_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libpq-12.9-h16c4e8d_3.conda
https://repo.anaconda.com/pkgs/main/linux-64/libwebp-1.2.4-h11a3e52_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/nss-3.89.1-h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/python-3.10.11-h7a1cb2a_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/absl-py-1.4.0-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/alabaster-0.7.12-pyhd3eb1b0_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/appdirs-1.4.4-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/async-timeout-4.0.2-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/attrs-22.1.0-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/backcall-0.2.0-pyhd3eb1b0_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/blinker-1.4-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/cachetools-4.2.2-pyhd3eb1b0_0.conda
https://conda.anaconda.org/conda-forge/noarch/certifi-2023.5.7-pyhd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/noarch/charset-normalizer-2.0.4-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/click-8.0.4-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/cloudpickle-2.2.1-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/colorama-0.4.6-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/curio-1.4-pyhd3eb1b0_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/cycler-0.11.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/dataclasses-0.8-pyh6d0b6a4_7.conda
https://repo.anaconda.com/pkgs/main/noarch/decorator-5.1.1-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/docutils-0.18.1-py310h06a4308_3.conda
https://repo.anaconda.com/pkgs/main/noarch/executing-0.8.3-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/frozenlist-1.3.3-py310h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/future-0.18.3-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/gast-0.4.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/greenlet-2.0.1-py310h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/idna-3.4-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/imagesize-1.4.1-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/kiwisolver-1.4.4-py310h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/llvmlite-0.40.0-py310he621ea3_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/lz4-4.3.2-py310h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/markdown-3.4.1-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/markupsafe-2.1.1-py310h7f8727e_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl-service-2.4.0-py310h5eee18b_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/multidict-6.0.2-py310h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/noarch/munkres-1.1.4-py_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/networkx-2.8.4-py310h06a4308_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/packaging-23.0-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/parso-0.8.3-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pickleshare-0.7.5-pyhd3eb1b0_1003.conda
https://repo.anaconda.com/pkgs/main/linux-64/pillow-9.4.0-py310h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/ply-3.11-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/psutil-5.9.0-py310h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/noarch/ptyprocess-0.7.0-pyhd3eb1b0_2.conda
https://repo.anaconda.com/pkgs/main/noarch/pure_eval-0.2.2-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/py4j-0.10.9.3-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pyasn1-0.4.8-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pycparser-2.21-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pygments-2.15.1-py310h06a4308_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/pyjwt-2.4.0-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pyparsing-3.0.9-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pysocks-1.7.1-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/python-flatbuffers-2.0-pyhd3eb1b0_0.conda
https://conda.anaconda.org/conda-forge/linux-64/python_abi-3.10-2_cp310.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pytz-2022.7-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pytzdata-2020.1-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pyyaml-6.0-py310h5eee18b_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/qt-main-5.15.2-h327a75a_7.conda
https://repo.anaconda.com/pkgs/main/linux-64/ruamel_yaml-0.15.100-py310h7f8727e_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/setuptools-67.8.0-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/six-1.16.0-pyhd3eb1b0_1.conda
https://repo.anaconda.com/pkgs/main/noarch/snowballstemmer-2.2.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/sphinxcontrib-applehelp-1.0.2-pyhd3eb1b0_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/sphinxcontrib-devhelp-1.0.2-pyhd3eb1b0_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/sphinxcontrib-htmlhelp-2.0.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/sphinxcontrib-jsmath-1.0.1-pyhd3eb1b0_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/sphinxcontrib-qthelp-1.0.3-pyhd3eb1b0_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/sphinxcontrib-serializinghtml-1.1.5-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/termcolor-2.1.0-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/toml-0.10.2-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/tornado-6.2-py310h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/tqdm-4.65.0-py310h2f386ee_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/traitlets-5.7.1-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/typing_extensions-4.6.3-py310h06a4308_0.conda
https://conda.anaconda.org/conda-forge/noarch/validobj-1.0-pyhd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/noarch/wcwidth-0.2.5-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/wheel-0.38.4-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/wrapt-1.14.1-py310h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/zipp-3.11.0-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/aiosignal-1.2.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/asttokens-2.0.5-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/astunparse-1.6.3-py_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/babel-2.11.0-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/blessings-1.7-py310h06a4308_1002.conda
https://repo.anaconda.com/pkgs/main/linux-64/cffi-1.15.1-py310h5eee18b_3.conda
https://repo.anaconda.com/pkgs/main/noarch/commonmark-0.9.1-pyhd3eb1b0_0.conda
https://conda.anaconda.org/conda-forge/linux-64/fiatlux-0.1.2-py310heac68b4_0.conda
https://repo.anaconda.com/pkgs/main/noarch/fonttools-4.25.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/google-pasta-0.2.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/importlib-metadata-6.0.0-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/jedi-0.18.1-py310h06a4308_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/jinja2-3.1.2-py310h06a4308_0.conda
https://conda.anaconda.org/conda-forge/noarch/latexcodec-2.0.1-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/lhapdf-6.5.0-py310hd41b1e2_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/matplotlib-inline-0.1.6-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/numpy-base-1.24.3-py310hb5e798b_1.conda
https://repo.anaconda.com/pkgs/main/noarch/pexpect-4.8.0-pyhd3eb1b0_3.conda
https://repo.anaconda.com/pkgs/main/linux-64/pip-23.1.2-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/prompt-toolkit-3.0.36-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pyasn1-modules-0.2.8-py_0.conda
https://repo.anaconda.com/pkgs/main/noarch/python-dateutil-2.8.2-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/qt-webengine-5.15.9-hd2b0992_4.conda
https://repo.anaconda.com/pkgs/main/noarch/rsa-4.7.2-pyhd3eb1b0_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/sip-6.6.2-py310h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/sqlalchemy-1.4.39-py310h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/tensorboard-plugin-wit-1.8.1-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/werkzeug-2.2.3-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/yarl-1.8.1-py310h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/aiohttp-3.8.3-py310h5eee18b_0.conda
https://packages.nnpdf.science/public/linux-64/apfel-3.0.6.3-hbdda60e_9.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/brotlipy-0.7.0-py310h7f8727e_1002.conda
https://repo.anaconda.com/pkgs/main/linux-64/cryptography-39.0.1-py310h9ce1e76_0.conda
https://repo.anaconda.com/pkgs/main/noarch/importlib_metadata-6.0.0-hd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pendulum-2.1.2-pyhd3eb1b0_1.conda
https://repo.anaconda.com/pkgs/main/noarch/prompt_toolkit-3.0.36-hd3eb1b0_0.conda
https://conda.anaconda.org/conda-forge/noarch/pybtex-0.24.0-pyhd8ed1ab_2.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pyqt5-sip-12.11.0-py310h6a678d5_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/qtwebkit-5.212-h4eab89a_4.conda
https://repo.anaconda.com/pkgs/main/linux-64/rich-12.5.1-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/stack_data-0.2.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/ipython-8.12.0-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/oauthlib-3.2.2-py310h06a4308_0.conda
https://conda.anaconda.org/conda-forge/linux-64/pybtex-docutils-1.0.2-py310hff52083_2.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pyopenssl-23.0.0-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pyqt-5.15.7-py310h6a678d5_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/urllib3-1.26.16-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/requests-2.29.0-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pooch-1.4.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/requests-oauthlib-1.3.0-py_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/sphinx-5.0.2-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/recommonmark-0.6.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/sphinx_rtd_theme-1.1.1-py310h06a4308_0.conda
https://conda.anaconda.org/conda-forge/noarch/sphinxcontrib-bibtex-2.5.0-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/numba-0.57.0-py310h0f6aa51_2.conda
https://conda.anaconda.org/conda-forge/linux-64/pineappl-0.6.0-py310hcb5633a_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/bottleneck-1.3.5-py310ha9d4c09_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/contourpy-1.0.5-py310hdb19cb5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/h5py-3.7.0-py310he06866b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/matplotlib-3.7.1-py310h06a4308_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/matplotlib-base-3.7.1-py310h1128e8f_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl_fft-1.3.6-py310h1128e8f_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl_random-1.2.2-py310h1128e8f_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/numpy-1.24.3-py310h5f9d8c6_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/numexpr-2.8.4-py310h85018f9_1.conda
https://repo.anaconda.com/pkgs/main/noarch/opt_einsum-3.3.0-pyhd3eb1b0_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/scipy-1.10.1-py310h5f9d8c6_1.conda
https://conda.anaconda.org/conda-forge/noarch/hyperopt-0.2.7-pyhd8ed1ab_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/keras-preprocessing-1.1.2-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pandas-1.5.3-py310h1128e8f_0.conda
https://conda.anaconda.org/conda-forge/noarch/banana-hep-0.6.8-pyhd8ed1ab_0.conda
https://packages.nnpdf.science/public/noarch/reportengine-0.30.28-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/seaborn-0.12.2-py310h06a4308_0.conda
https://conda.anaconda.org/conda-forge/noarch/eko-0.13.5-pyhd8ed1ab_0.conda
